permaweb/HyperBEAM

.editorconfig
.gitignore
.gitpod.yml
.husky/commit-msg
.husky/pre-commit
README.md
package-lock.json
package.json
rebar.config

chore(repo): tooling for conventional commits, erlfmt, and md formatting #1

---

package.json
rebar.config

According to our styling guide, and Sam's request we postpone using erlfmt for now

chore: unmerge erlfmt

---

src/hb_private.erl

Small improvement, but mostly just testing the PR workflow.

fix: don't cast binary to list before priv check.

---

src/dev_message.erl
src/dev_process.erl
src/dev_scheduler.erl
src/dev_scheduler_interface.erl
src/dev_scheduler_registry.erl
src/dev_scheduler_server.erl
src/hb_cache.erl
src/hb_client.erl
src/hb_message.erl
src/hb_opts.erl
src/hb_pam.erl
src/hb_path.erl

Additionally:
- Introduces the basis of `dev_process`, which will be our wrapper for AO processes.
- Adds some wrapper functions for hb_cache during the period of transition to everything-is-a-map.

feat: implements scheduling using maps and PAM.

---

src/dev_process.erl
src/dev_scheduler.erl
src/hb.app.src
src/hb_cache.erl
src/hb_opts.erl
src/hb_store.erl
src/hb_store_rocksdb.erl

- Update hb_cache to run tests with both fs and rocks backends
- Make a global switch to rocksdb_backend so it's used in all other tests
- Fix failing tests

fix(hb_store): fix hb_rocksdb_store so it works with hb_cache tests

---

src/hb_codec_converge.erl
src/hb_singleton.erl

rebar3 eunit -m hb_singleton
....
hb_singleton: path_parts_test...ok
[done in 0.088 s]
=======================================================
Failed: 5.  Skipped: 0.  Passed: 6.
I still have problems understanding how some of the parts should operate. E.g., how to build messages if the base message is provided in the form of hash, or how to process <<"path">> type of messages properly. But at least some of them are fixed.

fix: fix some tests in hb_singleton

---

src/dev_message.erl
src/hb_http_signature.erl
src/hb_message.erl

chore: reorg http-sig and hb_message as groundwork for signature devices

---

src/ar_http.erl
src/dev_json_iface.erl
src/dev_meta.erl
src/dev_process.erl
src/dev_process_cache.erl
src/dev_relay.erl
src/dev_router.erl
src/dev_scheduler_server.erl
src/dev_stack.erl
src/hb_codec_converge.erl
src/hb_codec_http.erl
src/hb_http.erl
src/hb_http_server.erl
src/hb_http_signature.erl
src/hb_message.erl
src/hb_opts.erl
src/hb_persistent.erl

```
[done in 83.697 s]
=======================================================
All 395 tests passed.
```

feat: add `dev_meta` functionality and tests, `dev_relay` draft, and fix all tests.

---

src/dev_codec_httpsig_conv.erl

fix(dev_codec_httpsig_conv): only omit content-type if HyperBEAM http encoding

---

src/dev_codec_httpsig_conv.erl
src/dev_wasi.erl

Passes the testsuite in `hb_message`. However, whenever I try to run the full project test suite, it seems to stall out and hang indeterminately.

feat(hb_codec_httpsig_conv): flatten body to single depth, in lieu of nested multipart.

---

src/hb_cache_render.erl

Adjust cache renderer to add support for RocksDB
alongside existing functionality.

feat: adjust cache renderer to support RocksDB

---

src/dev_process.erl
src/dev_push.erl
src/hb_opts.erl

Correctly change the push-target, in-light of the `hint` additions.

fix: push target calculation

---

src/dev_delegated_compute.erl
src/dev_faff.erl
src/dev_process.erl
src/dev_push.erl
src/dev_scheduler.erl
src/hb_examples.erl

Fixes the test suite for v0.8.

chore: v0.8 test fixes

---

rebar.config
src/dev_codec_json.erl
src/dev_hyperbuddy.erl
src/hb_http_server.erl
src/hb_opts.erl
src/html/hyperbuddy@1.0/console.html
src/html/hyperbuddy@1.0/index.html

h/t to @viksit's console implementation.

feat: add console, impl default HTTP req, fix device rendering

---

rebar.config
src/ar_bundles.erl
src/ar_tx.erl
src/dev_codec_ans104.erl
src/dev_codec_httpsig.erl
src/dev_dedup.erl
src/dev_json_iface.erl
src/dev_message.erl
src/dev_process.erl
src/dev_push.erl
src/dev_scheduler.erl
src/hb_converge.erl
src/hb_singleton.erl
src/hb_store_gateway.erl
src/hb_util.erl

This PR tries to resolve some warnings and some dialyzer issues regarding unused code or invalid return types.
Not everything is resolved but some can reduce the amount of issues returned by dialyzer or compilation.

chore: fix some warning and dialyzer issue

---

docs/intro.md

Provides a document to describe the reason, the needs for AO and how Converge protocol enables new era of decentralized computing system

docs: Add introduction doc

---

src/html/hyperbuddy@1.0/console.html
src/html/hyperbuddy@1.0/devices.js
src/html/hyperbuddy@1.0/utils.js

- json view for headers, multi part and json responses
get headers example
post example
meta info
- full screen mode
- expand / collapse json
- no need to type GET by default / means GET

update console with a few qol features

---

src/dev_json_iface.erl
src/dev_process.erl
src/dev_scheduler.erl
src/dev_scheduler_server.erl
src/dev_stack.erl
src/hb_cache.erl
src/hb_store_gateway.erl

This PR aims to reduce test flakiness and dependency on execution order by implementing proper setup and better timeout management.

Improve tests reliability

---

src/dev_cron.erl
src/dev_test.erl
src/hb_http_server.erl

This PR reconciles @viksit 's work on #221 with main.

feat: `~cron@1.0` merge

---

src/dev_lua.erl
test/hyper-aos.lua

Adds authority checks & msg.reply to Lua HyperAOS. PR details: implements message filtering based on trusted authorities (defined externally) and introduces a msg.reply() function for simplified responses.

feat: updated hyper-aos to check for authorities

---

src/dev_lookup.erl
src/dev_poda.erl
src/dev_scheduler_registry.erl
src/hb_ao.erl
src/hb_event.erl
src/hb_http_server.erl
src/hb_tracer.erl

This PR helps to maintain a better consistency of the codebase style guide.

chore: ensure codestyle consistency

---

src/dev_lua.erl

This PR aims to restore the seamless loading of our Lua scripts by leveraging Arweave transaction IDs as an option for the dev_Lua device.
Process Message Example:
```lua
#{
<<"device">> => <<"process@1.0">>,
<<"execution-device">> => <<"lua@5.3a">>,
<<"scheduler-device">> => <<"scheduler@1.0">>,
<<"script">> => <<"DosEHUAqhl_O5FH3vDqPlgGsG92Guxcm6nrwqnjsDKg">>
}
```

fix: script loading by tx in dev_lua

---

src/dev_hyperbuddy.erl
src/hb_cache_render.erl
src/html/hyperbuddy@1.0/graph.html
src/html/hyperbuddy@1.0/graph.js
src/html/hyperbuddy@1.0/index.html
src/html/hyperbuddy@1.0/styles.css

Adds heavily improved cached visualization and a web renderer.

feat: added cache visualizer v2

---

scripts/dynamic-router.lua
src/dev_router.erl
src/dev_snp.erl
src/hb_opts.erl

fix: trusted -> snp_trusted | update registration in lua script | snp_trusted is map

---

src/dev_codec_ans104.erl

This brings the HyperBEAM implementation's handling of ANS-104 items inline with the legacynet AO implementation.
All tests, bar the remaining issues from #271 (which are being reconciled in #278).

impr: force certain values to be ANS-104 tags, rather than base fields.

---

.vscode/settings.json
src/dev_green_zone.erl
src/dev_router.erl
src/dev_volume.erl
src/hb_opts.erl

**Description:**
This PR strengthens the security and consistency of volume management and device parameter validation throughout the HyperBEAM system.
**Key Enhancements:**
* **Secure Volume Configuration**
* All volume parameters must now be explicitly provided—no defaults are assumed
* Detailed validation added with descriptive error messages to avoid misconfiguration
* Volume operations are gated behind strict `hb_opts:check_required_opts` checks
* `volume@1.0` is officially registered in the HyperBEAM device registry
* **Improved Documentation and API Exposure**
* Introduced `info/1` and `info/3` across `volume` , `router` and `greenzone` devices to expose structured API details
* Standardized all device documentation using `@doc` annotations and added type specs
* Described expected …

feat(volume): enforce secure config and unify validation across devices
