permaweb/HyperBEAM

README.md
docs/gathering-metrics-locally.md
metrics/docker-compose.yml
metrics/grafana/provisioning/dashboards.yaml
metrics/grafana/provisioning/datasources/datasources.yaml
metrics/prometheus.yml
rebar.config
src/hb.app.src
src/hb_http_router.erl
src/hb_metrics_collector.erl

- use prometheus and prometheus_cowboy libraries to expose node metrics via /metrics endpoint;
- introduce custom `ao_metrics_collector` that allows collecting application-specific metrics (Load average and Uptime);
- introduce docker-compose setup that allows bringing up local infrastructure for Prometheus and Grafana (+ dashboard defined in JSON) on local machines

feat(metrics): introduce Erlnag VM metrics

---

.githooks/_/install.sh
.githooks/commit-msg
.gitignore
Makefile
README.md

This PR adds a zero-dependency simple convention for creating and installing git hooks. This convention establishes developer feedback loops, as part of normal git flow, great for early stage quality checks ie. at commit or push time.
Simply run `make githooks` to install any git supported hooks from the `.githooks` directory.
This PR also implements a `commit-msg` hook that ensures the commit message follows [Conventional Commits Style](https://www.conventionalcommits.org/en/v1.0.0/).

chore(repo): add simple githooks convention and enforce conventional commits

---

src/ar_bundles.erl
src/hb_opts.erl
src/hb_store_rocksdb.erl

tests seem to work well on my machine:
```
rebar3 eunit
===> Verifying dependencies...
make: Nothing to be done for `wamr'.
===> Analyzing applications...
===> Compiling hb
Post-compile hooks executed
===> Performing EUnit tests...
======================== EUnit ========================
file "hb.app"
application 'hb'
module 'ar_bundles'
ar_bundles: test_no_tags...[0.496 s] ok
ar_bundles: test_with_tags...[0.155 s] ok
ar_bundles: test_unsigned_data_item_id...ok
ar_bundles: test_unsigned_data_item_normalization...ok
ar_bundles: test_empty_bundle...[0.010 s] ok
ar_bundles: test_bundle_with_one_item...[0.001 s] ok
ar_bundles: test_bundle_with_two_items...[0.001 s] ok
ar_bundles: test_recursive_bundle...[2.559 s] ok
ar_bundles: test_bundle_map...[1.175 s] ok
ar_bundles: …
```

feat(hb_store): switch local_store to hb_store_rocksdb

---

src/dev_process.erl
src/dev_process_cache.erl
src/dev_test.erl
src/dev_wasm.erl
src/hb_beamr.erl
src/hb_message.erl
src/hb_opts.erl

This PR implements the new WASM device with compatibility for execution inside a `dev_process` with Converge. It also uses Converge for import resolutions, such that these, too, generate hashpaths, can be executed remotely, etc. See commit log for full list of changes.

feat: `dev_wasm` process execution flow

---

src/dev_json_iface.erl
src/dev_message.erl
src/dev_process.erl
src/dev_process_worker.erl
src/dev_scheduler.erl
src/dev_stack.erl
src/dev_test.erl
src/dev_wasi.erl
src/dev_wasm.erl
src/hb.erl
src/hb_beamr.erl
src/hb_beamr_io.erl
src/hb_converge.erl
src/hb_message.erl
src/hb_opts.erl
src/hb_persistent.erl
src/hb_private.erl
src/hb_sup.erl
src/hb_util.erl

Also adds support for multiple clients of the WASM port using a wrapper process.
See full commit log for details.
Tests:
```
sam@Sams-MacBook-Pro hyperbeam % rebar3 eunit
===> Verifying dependencies...
make: Nothing to be done for `wamr'.
===> Analyzing applications...
===> Compiling hb
Post-compile hooks executed
===> Performing EUnit tests...
======================== EUnit ========================
file "hb.app"
application 'hb'
module 'ar_bundles'
ar_bundles: test_no_tags...[0.109 s] ok
ar_bundles: test_with_tags...[0.163 s] ok
ar_bundles: test_bundle_with_zero_length_tag...ok
ar_bundles: test_unsigned_data_item_id...ok
ar_bundles: test_unsigned_data_item_normalization...ok
ar_bundles: test_empty_bundle...[0.003 s] ok
ar_bundles: test_bundle_with_one_item...ok
ar_bundles: …
```

feat: `dev_process` push with Converge and `hb_persistent` execution for `/Compute`

---

src/dev_process.erl
src/dev_process_cache.erl
src/dev_stack.erl
src/dev_test.erl
src/dev_wasm.erl
src/hb_cache.erl
src/hb_cache_control.erl
src/hb_codec_converge.erl
src/hb_converge.erl
src/hb_opts.erl
src/hb_path.erl
src/hb_private.erl
src/hb_store.erl
src/hb_util.erl

This version stores snapshot data in the 'old' way, where multipart paths are used, rather than hashpaths. Works fine for now, but later we can neaten it up.
Also includes:
- Mapping across `dev_stack`s
- Various improvements (timeouts on tests, etc).
*Horrendous* performance at the moment, caused by excessive repeated ID generations. Shooting to close the gap on BETA-1/2 goals first, then we can look at those. Will be an easy fix when we have a moment for it.
All 337 tests passing.

impl process restore from snapshot

---

src/hb_converge.erl
src/hb_http_benchmark_tests.erl
src/hb_persistent.erl

Previously the group leader was not monitored during the converge resolution stage. As a result, the awaiting process would hang for an infinite amount of time, if the leader exited before the message was delivered.
Now we monitor the leader process and re-try if it exits.

fix(hb_converge): monitor group leader during resolution

---

src/hb_codec_http.erl
src/hb_http_structured_fields.erl

This PR implements the start of the `http` codec. This passes the `hb_message` codec testsuite EXCEPT for signature test cases:
```
{"signed item to message and back test", fun signed_message_encode_decode_verify_test/1},
{"signed item to tx and back test", fun signed_tx_encode_decode_verify_test/1},
{"signed deep serialize and deserialize test", fun signed_deep_tx_serialize_and_deserialize_test/1},
```
As mentioned, signature is still not working, and what I am focusing on now, but wanted to get this PR up since the changes were getting to be pretty dense.
I'll also need to write a test ensuring a `body` key will be properly encoded as the `inline` Content-Disposition in the Http multi-part response.

Start Http Codec

---

src/dev_wasm.erl
src/hb_private.erl

The current test run shows 6 passing tests. However, I have managed to lock the BEAM by:
```
imported_function_test_() ->
% Manages to spoil everything. Looks like the beamr sends import request
% but we never get it
{timout, 10, imported_function_test()}.
```
E.g. the driver code successfully sends a request to the host machine to do the imported function call, but it appears like no one is listening to those. I am exploring the case deeper [as soon as it's also seems related to the issue I saw on another machine earlier]

fix: fix most of dev_wasm test cases (fix incorrect key values)

---

src/hb_util.erl

Use string:lowercase/1 instead of obsolete string:to_lower/1

fix: use string:lowecase for binary lowecase conversion

---

src/hb_codec_http.erl

Since signature and signature input will always be encoded as structured field dictionaries, we still need to parse signature params as `BareItems`, so this PR adds this bit back to `from_signature`

fix(hb_http_codec): properly parse value from signature param bare item #13

---

src/hb_codec_http.erl
src/hb_http.erl

Also fixes a compilation error introduced in fb7df6c
```
hb_message: -generate_test_suite/1-fun-1- (http: basic map codec test)...[0.001 s] ok
hb_message: -generate_test_suite/1-fun-1- (http: set body codec test)...ok
hb_message: -generate_test_suite/1-fun-1- (http: match test)...ok
hb_message: -generate_test_suite/1-fun-1- (http: single layer message to encoding test)...ok
hb_message: -generate_test_suite/1-fun-1- (http: message with large keys test)...ok
hb_message: -generate_test_suite/1-fun-1- (http: nested message with large keys and content test)...ok
hb_message: -generate_test_suite/1-fun-1- (http: simple nested message test)...ok
hb_message: -generate_test_suite/1-fun-1- (http: nested message with large content test)...[0.001 s] ok
hb_message: -generate_test_suite/1-fun-1- (http: …
```

feat(hb_codec_http): properly encode and decode body, distinguishing between multiple keys or sole body key #13

---

src/dev_faff.erl
src/dev_meta.erl
src/dev_p4.erl
src/dev_simple_pay.erl
src/hb_http.erl
src/hb_http_server.erl
src/hb_opts.erl

Features two simple payment devices:
- `faff@1.0`, offering 'friends and family' private access to a node's services; and
- `simple-pay@1.0`, offering static pricing in a current managed by the node operators discretion. This pattern allows node operators to offer fiat payments to users through the normal payment mechanisms (CC, etc), then send a request to their node to update that user's balance -- akin to ArDrive's Turbo service for Arweave.

feat: impl p4

---

src/hb_codec_http.erl
src/hb_message.erl

This issue was introduced in #84
The root problem was that, during encoding, the "body only" nested messages were being encoded following that rule. This was effectively "collapsing" the nested "body only" messages into the body of the top message, but with an additional CRLF added at each layer.  So then on parsing, those added CRLF would end up being parsed as part of the top level body, thus invalidating it.
Basically, "body-only" nested messages require different behavior, in order to preserve the hierarchy of nesting. That behavior is implemented in this PR.
See comments for further details.

fix(hb_codec_http): ensure nested message structure is preserved, even with only sub bodies #13

---

docs/converge-http-api.md
src/dev_process.erl
src/dev_scheduler.erl
src/dev_wasm.erl
src/hb_codec_converge.erl
src/hb_codec_http.erl
src/hb_http_structured_fields.erl
src/hb_singleton.erl

Implements the following API syntax changes:
`...!device` => `...~device`.
`...key1=val1&key2=val2` => `...&key1=val1&key2=val2`
`...|type` => `...+type`
Additionally, lists and maps can be represented inline in a single HTTP key using the `+list` and `+map` calls, which automatically convert to the appropriate Erlang type using the RFC 8941 rules.
Still to add: `*` auto type modifier.

impr: `hb_singleton` syntax improvements

---

src/dev_meta.erl
src/dev_relay.erl
src/dev_router.erl
src/hb_converge.erl
src/hb_http.erl
src/hb_message.erl
src/hb_opts.erl
src/hb_singleton.erl

This PR reorganizes `dev_relay` such that the core resolution logic is shared to with `hb_http`. It also fixes a subtle issue with parsing singleton paths that contain multiple slashes in a row (URIs, for example).
To use, start a HB node and call:
```
curl /~relay@.1.0/call?method=GET?0.path=https://www.arweave.net/
```

impr: `dev_relay`

---

src/hb_beamr.erl

Instead of loading the **beamr** lib from a relative priv directory `erl_ddll:load("./priv` I am now loading using `code:priv_dir(_APP)` this should allow us the run **beamr** in release.

fix: dynamically getting priv directory to load beamr

---

src/dev_meta.erl
src/hb_opts.erl

Nodes with `initialized == false` will not execute operations until the node has received a new node message. Nodes with `permanent` as their `initialized` value will return an error if `POST /~meta@1.0/info` is employed.

feat: `initialized` parameter for `dev_meta`.

---

src/dev_codec_httpsig.erl
src/dev_scheduler.erl
src/hb_http.erl

Also fixes issue in `dev_codec_httpsig:hmac/1` where it was producing an invalid signature base. `dev_codec_httpsig:signature_base/3` should be used/composed upon wherever possible, as it encapsulates the 9421 rules for extracting components from message context, encoding signature parameters, and properly producing a signature base.
Also fixes some 9421 implementation logic (although HB most likely will not hit those branches)
Finally, ensures consistent ordering of component identifiers is used.

fix(hb_http): strip fields, not signed, from the incoming message

---

native/hb_beamr/hb_wasm.c
src/hb.erl
src/hb_http_benchmark_tests.erl
src/hb_http_server.erl

Now it also cleans up the import_results structure, that allows to decrease the memory leakage even more:
```
{driver_alloc,0.40625}
{driver_alloc,0.65625}       -> first run
{driver_alloc,0.65625}.      -> second run
{driver_alloc,0.65625}.      -> third run
```

fix(hb_beamr): clean up memory allocated for storing import results

---

src/hb_singleton.erl

The to/1 function enables conversion of converge messages into TABM format.

feat(hb_singleton): implement to/1 function for TABM conversion

---

.gitignore
src/hb_cache_render.erl

I have implemented fs-based hb_cache_renderer, based on the brief from yesterday.
Please find the attached graph examples it builds, to verify if that's what we needed.

chore: implement fs based cache keys render

---

src/dev_p4.erl
src/dev_router.erl
src/dev_simple_pay.erl

Adds support for:
- Operator defined non-chargable routes, which bypass the pricing and ledger devices
- A unified `balance` endpoint, which wraps the underlying ledger device's `balance`

p4 improvements

---

src/dev_meta.erl
src/hb_converge.erl
src/hb_gateway_client.erl
src/hb_http_server.erl
src/hb_store_gateway.erl
src/hb_store_graphql.erl
src/hb_store_remote_node.erl

This PR allows HyperBEAM nodes to enable any Arweave graphql API endpoint + any gateways that serve data to be used in conjunction to enable decentralized access to data from the network.
HyperBEAM now comes pre-configured to get data from both the `arweave.net` and Goldsky graphql indexes. These can be added to/overriden by changing the node message of the server either by using `POST /~meta@1.0/info`on a live node, setting the routes in the node start call, or changing the defaults in `hb_opts`.

impl: Arweave gateways as `hb_store` accessible data repositories

---

src/hb_http.erl
src/hb_http_server.erl

Adds default CORS headers to message responses. If headers are set already by the user those will override the defaults returned. This ensures that httpsig messages remain verifiable.

feat: add support for CORS headers used by browsers

---

src/dev_delegated_compute.erl
src/dev_genesis_wasm.erl
src/dev_patch.erl
src/dev_process.erl
src/hb.erl
src/hb_cache_render.erl
src/hb_http_server.erl
src/hb_opts.erl

Also changes a couple of other areas:
- `process@1.0/now` endpoint returns the full state, so that patched state can be accessed by `/procID/now/stateName`.
- `hb_cache_render` options improvements

feat: add a device that searches the `patch-from` location and applies patch messages

---

src/dev_codec_httpsig_conv.erl
src/dev_message.erl
src/dev_meta.erl
src/dev_test.erl
src/hb_cache.erl
src/hb_store_gateway.erl

Still some debugging to do, but this PR provides a fallback and additional error generation, surfacing issues safely and quickly.

impr: cache writes for empty maps

---

src/hb_converge.erl
src/hb_converge_test_vectors.erl
src/hb_opts.erl
src/hb_util.erl
test/dev_dummy.erl

This PR implements loading devices by ID from Arweave or other `hb_store` compatible sources.
Additionally, it adds support for `requires-*` keys, which allows device authors to specify necessary properties about the machine in order to run the module. Currently, only direct binary matches against `erlang:system_info` are supported.

feat: enable device load from caches + Arweave

---

src/dev_codec_json.erl
src/dev_delegated_compute.erl
src/dev_json_iface.erl
src/dev_push.erl
src/dev_relay.erl
src/dev_scheduler.erl
src/dev_scheduler_cache.erl
src/dev_scheduler_formats.erl
src/dev_scheduler_server.erl
src/hb_cache.erl
src/hb_http.erl
src/hb_store_gateway.erl

This patch improves performance of `milestone 3` evaluation on an embedded legacy CU by approximately 30x (~97% eval time reduction).

feat: cache scheduler data and support POST of data items to `delegated-compute@1.0`.

---

src/dev_cache.erl
src/hb_cache.erl
src/hb_http_server.erl
src/hb_opts.erl
src/hb_store_fs.erl
src/hb_store_remote_node.erl

Implements @pete's remote-node-as-store mechanism. The new `cache@1.0` device that it brings allows you to not just read all data from the caches of other nodes, but also to write to the store if the node trusts the request.

feat: remote node store

---

src/dev_delegated_compute.erl
src/dev_process.erl
src/dev_relay.erl
src/dev_scheduler.erl
src/dev_scheduler_formats.erl
src/hb_persistent.erl
src/hb_util.erl

This PR lowers the per-slot eval time on a typical AOS legacynet process (`oQZQd1-MztVOxODecwrxFR9UGUnsrX5wGseMJ9iSH38` was used for sampling) from ~250-300ms to 114ms on reference hardware. This PR builds on #184, before which execution on our reference process took approximately 3-5 seconds per slot.
Each commit gives an itemized description of the changes.

impr: process@1.0 and scheduler@1.0 async caching optimizations

---

native/hb_beamr/hb_wasm.c
native/hb_beamr/include/hb_wasm.h

Currently causes a build error for Clang 19:
```
===> Compiling /Users/elliot/Code/AO/Core/Fork/HyperBEAM/native/hb_beamr/hb_beamr.c
===> In file included from /Users/elliot/Code/AO/Core/Fork/HyperBEAM/native/hb_beamr/hb_beamr.c:4:
native/hb_beamr/include/hb_wasm.h:63:55: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
63 | int wasm_execute_exported_function(Proc* proc, const *function_name, wasm_val_t* params, wasm_val_t * results);
|                                                ~~~~~  ^
|                                                int
```

fix(beamr): explicit argument type in `wasm_execute_exported_function`

---

rebar.config
rebar.lock
src/dev_scheduler.erl
src/hb.app.src
src/hb.erl
src/hb_http_server.erl
src/hb_store.erl
src/hb_store_rocksdb.erl
src/hb_test_utils.erl

In order to compile HyperBEAM with rocksdb support, you should now run `rebar3 as rocksdb compile` (where `compile` can be replaced by any other function you wish to run). This eliminates one of the more complex dependencies for building HyperBEAM for newbies. More advanced users will still likely still want to use rocksdb or another store implementation.

feat: rocksdb as compile option

---

rebar.config

Updates `quicer` from https://github.com/qzhuyan/quic/commit/97d8be9fb8017f4578248f96f5b35f8e357df792 [0.1.11-pre1](https://github.com/qzhuyan/quic/releases/tag/0.1.11-pre1) to https://github.com/emqx/quic/commit/e2e9ab3e1ec53e20d5f9401359cc6ee8f971d112 [0.1.11](https://github.com/emqx/quic/releases/tag/0.1.11)
Notably, it fixes https://github.com/microsoft/msquic/pull/4744 affecting some versions of Clang. Does not introduce any regressions when running `rebar3 as http3 eunit`

fix(http3): quicer version

---

.gitignore
Makefile
rebar.config
rebar.lock
src/dev_genesis_wasm.erl
src/hb_features.erl

Add functionality to run a Compute Unit (CU) server alongside HyperBEAM via a rebar3 profile. This allows developers to start a local CU server with `rebar3 as cu shell`.
- Add cu feature flag in hb_features.erl
- Create Makefile targets for setup-cu, start-cu, and stop-cu
- Configure rebar.config with cu profile hooks
- Add cu/ directory to .gitignore

feat: add CU server integration with rebar3 profile

---

src/dev_genesis_wasm.erl
src/hb_http.erl

This allows developers to start another server on :6363 and execute against it for debugging purposes. If no server is running and the `as genesis_wasm` flag is set, a new node will be started.
Also fixes an errant `hb_converge` call introduced in #203.

impr: use existing genesis-wasm@1.0 server if already running

---

Makefile
src/dev_codec_httpsig.erl
src/dev_codec_httpsig_conv.erl
src/dev_codec_structured.erl
src/dev_genesis_wasm.erl
src/dev_json_iface.erl
src/dev_message.erl
src/hb.erl
src/hb_escape.erl
src/hb_message.erl
src/hb_structured_fields.erl
src/hb_util.erl

This PR introduces a new `ao-ids` key to `httpsig@1.0` encoded messages that contain all elements of the message that have an ID as their key, as well as an immediate binary value. This is necessary because HTTP/2+3 require lower case keys. The alternative -- lower-casing all IDs -- would make encoding information-lossy and lead to lost idempotency. Lowering all IDs across the protocol is possible in theory, but would lead to security of 43 character (traditionally 256-bit values) diminishing to around ~225 bits of security.
The encoding used by the `ao-ids` key is a 'relaxed' form of structured field dictionaries. In particular, upper-case keys are admissible in this encoding, as well as the typical `-` and `_` characters. As such, the `ao-ids` key is not listed in `ao-types`, such that …

impr: encode IDs in a grouped header, improve embedded legacynet executor

---

Makefile
native/genesis-wasm/launch-monitored.sh
src/dev_genesis_wasm.erl

This PR introduces a monitor to the `genesis-wasm@1.0` flow, which detects the termination of the parent HyperBEAM node and reciprocally closes the child execution server. This allows the pair to neatly boot and terminate together.

impr: kill child genesis-wasm executor on close of HyperBEAM

---

src/dev_message.erl
src/hb_message.erl
src/hb_util.erl

Fixes a bug in which the hashpath was sometimes lost during conversion between `structured@1.0`, TABM, and the target format. Hashpaths are always now seen in the `tag` element of each `signature-input` element.

fix: ensure hashpath is added to hsig message during conversion

---

rebar.config
src/dev_json_iface.erl
src/dev_lua.erl
src/dev_process.erl
src/dev_wasm.erl
src/hb_ao.erl
src/hb_examples.erl
src/hb_http.erl
src/hb_http_benchmark_tests.erl
src/hb_opts.erl
src/hb_util.erl
test/aos-2.0.4.lua
test/test.lua

This PR adds a HyperBEAM-native Lua execution device, built on Luerl.
Most AO processes are already built using Lua executed inside a sandboxed WASM environment. This PR allows for the execution of Lua code in Erlang's native execution environment, _outside_ of the sandbox (making it able to interact with all of HyperBEAM's native functions). This serves as the groundwork for allowing developers to build their own HyperBEAM/AO-Core devices in Lua, rather than needing to know Erlang in order to build.
The `~lua@5.3a` device handles all keys that are not directly part of its base message by executing the function with the corresponding name in its script. For example, if a base message with this device set receives a call for `preprocess` (used by `~meta@1.0` to preprocess all HTTP …

feat: Native Lua execution with the `~lua@5.3a` device

---

src/dev_lua.erl
src/dev_scheduler.erl
src/dev_wasi.erl
test/test.lua

This PR introduces optional lookahead readers of the local cache, parallelizing cache reads with process execution. In test scenarios, this patch improved performance for a `~lua@5.3a` process from ~55 executions per second to ~87.

feat: `~scheduler@1.0` async local cache lookahead workers

---

.vscode/launch.json
.vscode/tasks.json
rebar.config
src/hb_debugger.erl
src/hb_util.erl

As the moduledoc describes:
```
%%% @doc A module that provides bootstrapping interfaces for external debuggers
%%% to connect to HyperBEAM.
%%% 
%%% The simplest way to utilize an external graphical debugger is to use the 
%%% `erlang-ls' extension for VS Code, Emacs, or other Language Server Protocol
%%% (LSP) compatible editors. This repository contains a `launch.json'
%%% configuration file for VS Code that can be used to spawn a new HyperBEAM,
%%% attach the debugger to it, and execute the specified `Module:Function(Args)'.
%%% Additionally, the node can be started with `rebar3 debugging' in order to
%%% allow access to the console while also allowing the debugger to attach.
```

feat: impl spawning and breaking on HB functions via external debuggers

---

src/dev_manifest.erl
src/dev_router.erl
src/hb_opts.erl

Implements the standard as described here:
https://specs.ar.io/?tx=lXLd0OPwo-dJLB_Amz5jgIeDhiOkjXuM3-r0H_aiNj0
The only notable deviation from this standard is that callers must resolve `.../index` in order to receive the index page, as HyperBEAM does not (yet?) allow us to resolve empty string requests.

feat: implement path manifest resolver, following the v1 JSON standard

---

native/hb_beamr/hb_beamr.c

h/t to @jim-toth for the report! 🫡

fix: Correctly initialize `current_import` during port boot

---

src/dev_meta.erl
src/hb_ao.erl
src/hb_event.erl
src/hb_http_server.erl
src/hb_tracer.erl
src/include/hb.hrl

This PR adds a tracer to support AO's flow tracing in case of the error.
This allows to see the last steps of execution before to throw an error. 
For the user, it would have a nice response to identify the cause of the issue.

feat: Display 500 error by tracing steps of execution

---

src/dev_lua.erl
test/test.lua

Implements sandboxable access to AO-Core resolution from the `~lua@5.3a` device.
The sandbox whitelist can be set using the `device-sandbox` key in the base message to a list of devices.

feat: AO-Core resolver in Lua

---

src/dev_router.erl

This commit changes the router's preprocessing logic from a blacklist to a whitelist approach:
- Rename is_exempt to is_relevant and invert the preprocessing logic
- Replace DEFAULT_EXEMPT_ROUTES with DEFAULT_RELAVANT_ROUTES
- Only process ~process@1.0 paths, instead of exempting specific paths
- Remove unnecessary debug logging statements
- Fix tilde escape sequence in binary:split pattern
This approach makes message processing more predictable by explicitly defining what should be processed rather than what should be exempted.

feat: switch from exempt routes to relevant routes approach

---

src/dev_router.erl
src/dev_snp.erl
src/hb_opts.erl

This change refactors the SNP validation system to support multiple trusted configurations by consistently using lists of maps instead of single maps:
- Convert all trusted configuration structures from maps to lists of maps
- Update SNP trusted validation logic to check against multiple configurations
- Fix init function to properly append new configurations to existing list
- Update default configuration in hb_opts.erl to use empty list instead of map
This enables more flexible SEV-SNP validation by allowing multiple trusted measurement configurations to be stored simultaneously.

fix(snp): convert trusted configuration from map to list structure

---

src/dev_green_zone.erl
src/dev_meta.erl
src/dev_router.erl
src/dev_snp.erl
src/hb_http_server.erl
src/hb_opts.erl

This commit enhances security and consistency by:
1. Adding a centralized request validation mechanism in dev_meta:validate_request/2
2. Implementing signature verification for device initialization across green_zone, router, and SNP devices
3. Protecting sensitive data by stripping priv_wallet from node messages
4. Refactoring SNP device to use the trusted list structure instead of individual snp_hashes
5. Improving error handling with more descriptive messages
6. Setting operator to unclaimed by default in http_server
7. Adding utility function for binary data deserialization (load_bin)
These changes create a more secure initialization flow, ensuring only authorized users can modify critical device configuration.

feat: implement uniform request validation and improve security

---

src/dev_codec_flat.erl
src/dev_green_zone.erl
src/dev_local_name.erl
src/dev_meta.erl
src/hb_http.erl
src/hb_http_server.erl
src/hb_message.erl

This PR introduces support for:
- Decoding arbitrarily encoded messages, via use of the `codec-device` key, on HTTP-inbound;
- Adds `~meta@1.0` functionality for resolving the `admin`, `initiator`, and `operator` of a node. The roles operate as follows:
1. The `admin` role is granted to the `operator`, or any signer if the node has `operator: unclaimed`.
2. The `initiator` is the _set_ of signers of the first `POST /~meta@1.0/info` that the node received. The role check returns `true` if and only if _all_ of the signers of the initialization message are also present on the request. This allows, for example, sets of multiple individuals to operate a node together.
3. The `operator` role is defined simply by the value of the `operator` key in the node message.
To send messages encoded with …

feat: support arbitrary codec-device inbound via HTTP; add `role` resolution in `~meta@1.0`

---

src/dev_lua.erl

This patch enhances the script loading process to support retrieval of Lua scripts by ID.

chore: fix httpsig+ans104 compatibility in `lua@5.3a`

---

native/hb_keccak/hb_keccak.c
native/hb_keccak/hb_keccak_nif.c
native/hb_keccak/include/hb_keccak.h
rebar.config
src/ar_wallet.erl
src/dev_codec_ans104.erl
src/dev_json_iface.erl
src/hb_gateway_client.erl
src/hb_keccak.erl
src/hb_util.erl
src/include/hb.hrl

Implements the `hb_keccak` NIF, which takes in ECDSA owner keys and translates them to Ethereum addresses

feat: handle ecdsa sigs

---

src/hb_ao.erl
src/hb_http_server.erl
src/hb_singleton.erl

This PR introduces support for subresolution of sections of a path and individual keys in AO-Core. This allows requests to be constructed from the result of many different individual resolutions, as well as allowing static paths to lead to dynamic results.

feat: HTTP-accessible subresolution of keys and path parts

---

src/dev_router.erl

Replaced snp_hashes with the trusted in the opts passed to generating the attestation report.
NOTE: This is needed now because we removed snp_hashes in replace of trusted[1]

fix: using trusted instead of snp_hashes

---

src/dev_scheduler.erl

Scheduler requests from genesis wasm had accept header of `<<"application%2Faos-2">>`. This decodes that

feat: normalize accept format in scheduler

---

src/dev_genesis_wasm.erl
src/dev_message.erl
src/dev_patch.erl
src/dev_process.erl
src/hb_ao.erl

This PR introduces 2 major improvements:
1. `~message@1.0/set` now allows callers to `unset` keys in deep maps. This allows device builders and platform-level developers to more easily control state messages over multiple message executions.
2. An improved and generalized `patch@1.0` interface. This new interface introduces makes the device generally applicable for all application builders, rather than specially-purposed for use with `~process@1.0`. The `~genesis-wasm@1.0` device has been modified such that existing deployments of `~patch@1.0` will not be affected. The moduledoc describes the new interface as follows:
```
%%% @doc A device that can be used to reorganize a message: Moving data from
%%% one path inside it to another. This device's function runs in two modes:
%%%
%%% 1. When …
```

feat: improved `~patch` and `~message@1.0/set`

---

rebar.config
src/dev_meta.erl

This allows us to track the versions of HyperBEAM that different nodes in the network are executing. Additionally, as the build information is exposed through an AO-Core device (`~meta@1.0`) this response is itself attested by the node's key. This opens options for varied types of enforcement depending on correctness.

feat: expose `build` information on `~meta@1.0/build`.

---

src/dev_codec_ans104.erl
src/dev_delegated_compute.erl
src/dev_push.erl
src/dev_scheduler.erl
src/hb_opts.erl

Users may now request a `result-depth` along with `push` requests, allowing them to specify the depth to which the results of computations should be included in results given.
The effect of this is that the number of HTTP requests necessary for many (perhaps most?) uses of AO processes is cut in half. Rather than sending a request to schedule a result, then another to get the result, the user can simply `POST /procID/push` the message and receive the result. The effect of this is particularly pronounced, as _latency_ -- rather than execution speed -- is typically the bottleneck in creating 'snappy' user experiences with AO.
Additionally, this PR fixes two issues elsewhere in the codebase, on related codepaths:
1. An issue with the ANS-104 codecs that led to messages unnecessarily being …

impr: `~push@1.0` supports user-requested depth for compute results

---

src/dev_hook.erl
src/dev_scheduler.erl
src/dev_scheduler_cache.erl
src/hb_http_server.erl

Improves the interface for registering and retrieving scheduler-location records, including allowing nodes to notify others when their scheduler location is updated.
Additionally, the `dev_hook` interface has been updated to support requesting that the node sign requests before performing the hook execution, as well as the ability to have the result of the hook be discarded if preferred. Together, these two options make it significantly easier to integrate calls to non-hook-aware devices into hook calls.

impr: `scheduler@1.0/location` key

---

src/dev_scheduler.erl

This pr fixed the encoding uri format for the application/aos-2 setting.

fix: encoding issue when calling local scheduler
